// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77zWZxkbogxi5aDd2wO5uAMVjwiEqUK0',
    appId: '1:1023406537100:web:63add4ac7857d9bce27ea9',
    messagingSenderId: '1023406537100',
    projectId: 'my-projectcrud',
    authDomain: 'my-projectcrud.firebaseapp.com',
    storageBucket: 'my-projectcrud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgneSoo8uroyizBkwLVPqhnXdEHmWAQmk',
    appId: '1:1023406537100:android:a868155c78a38914e27ea9',
    messagingSenderId: '1023406537100',
    projectId: 'my-projectcrud',
    storageBucket: 'my-projectcrud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeA9nXcg0bOdAbp_A9OnGf9bDwPnzLqpo',
    appId: '1:1023406537100:ios:14f07e0093aa4c63e27ea9',
    messagingSenderId: '1023406537100',
    projectId: 'my-projectcrud',
    storageBucket: 'my-projectcrud.appspot.com',
    iosClientId: '1023406537100-u70qadpi2pbhpr96n5o942ihd00rvapt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
